name: tasbih
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Application version.
version: 1.0.0+1

# Flutter SDK environment.
environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies required for the project.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sqflite: ^2.0.0+4
  fl_chart: ^0.55.2
  url_launcher: 6.3.0
  google_fonts: 6.1.0
  path: ^1.8.3
  shared_preferences: ^2.2.3
  vibration: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: 2.2.19
  home_widget: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/icon.png"

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Adding assets.
  assets:
    - assets/background.png
    - assets/icon.png
    - assets/icon_big.png 
  


flutter_native_splash:
  color: "#FFFFFF"  # Background color (white)
  image: assets/icon_big.png 
  fullscreen: true  # Ensures fullscreen display
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icon_big.png 
    icon_background_color: "#FFFFFF"
  position: center  # Icon should be centered