name: tasbih
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Application version.
version: 1.0.0+1

# Flutter SDK environment.
environment:
  sdk: '>=3.2.3 <4.0.0'

# Dependencies required for the project.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  sqflite: ^2.0.0+4
  fl_chart: ^0.55.2
  url_launcher: 6.3.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter-specific settings.
flutter:
  uses-material-design: true

  # Adding assets.
  assets:
    - assets/background.png